version: '3.8'
services:
  backend:
    build:
      context: ./backend
      args:
        WORK_DIR: $WORK_DIR
    environment:
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_ROOT_PASS: $DB_ROOT_PASS
    volumes:
      - ./backend:$WORK_DIR
    command: sh -c "cd $BACK_PROJECT_NAME && python manage.py runserver 0:8000"
    ports:
      - "$BACK_PORT:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
    volumes:
      - db_store:/var/lib/mysql
    ports:
      - $DB_PORT:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db_store: