version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        WORK_DIR: $WORK_DIR
    volumes:
      - ./backend:$WORK_DIR
    command: ["python", "manage.py", "runserver", "0:8000"]
    ports:
      - "$BACK_PORT:8000"